export const agumon = {
  body: {
    width: 11,
    height: 14,
    offsetX: 0,
    offsetY: 0,
    gravityY: 900,
  },
  attacks: {
    main: {
      type: "projectile",
      anim: "attack-C",
      power: 0.5,
      damage: 1,
      impactVFX: "vfx-bomb-explosion",
      projectile: {
        texture: "fireball",
        anim: "fireball_fly",
        speed: 220,
        offsetX: 30,
        offsetY: 2,
        lifetime: 1900,
        statusEffect: "burn",
        hitReaction: "launch",
      },
      fireFrame: 5,
      cooldown: 800,
    },
    skill1: {
      type: "projectile",
      anim: "attack-E",
      power: 4,
      impactVFX: "vfx-gnd-blast",
      projectile: {
        motion: "arc",
        explosive: true,
        explodeOnGround: true,
        explosionRadius: 164,
        texture: "big-fireball",
        speed: 220,
        offsetX: 15,
        offsetY: -10,
        lifetime: 900,
      },
      fireFrame: 7,
      cooldown: 800,
    },
  },
  move: {
    speed: 200,
  },
  evolution: {
    prev: null,
    next: "greymon",
  },
};
