export const garuromon = {
  body: {
    width: 41,
    height: 34,
    offsetX: -2,
    offsetY: 0,
    gravityY: 900,
  },
  attacks: {
    main: {
      type: "projectile",
      anim: "attack-B",
      power: 0.5,
      damage: 1,
      impactVFX: "vfx-tiny-fire-impact",
      projectile: {
        texture: "fireball",
        anim: "fireball_fly",
        speed: 220,
        offsetX: 73,
        offsetY: -5,
        lifetime: 1900,
        statusEffect: "burn",
        hitReaction: "launch",
      },
      fireFrame: 5,
      cooldown: 800,
    },
    skill1: {
      type: "projectile",
      anim: "attack-A",
      power: 4,
      impactVFX: "vfx-gnd-blast",
      projectile: {
        motion: "arc",
        explosive: true,
        explodeOnGround: true,
        explosionRadius: 164,
        texture: "big-fireball",
        speed: 220,
        offsetX: 15,
        offsetY: -10,
        lifetime: 900,
      },
      fireFrame: 7,
      cooldown: 800,
    },
  },
  move: {
    speed: 200,
  },
  evolution: {
    prev: "gabumon",
    next: "imperialdramon",
  },
};
