export const ophanimon = {
  body: {
    width: 18,
    height: 40,
    offsetX: 0,
    offsetY: 0,
    gravityY: 900,
  },
  movement: {
    mode: "multi-domain",
    domains: ["ground", "air"],
    default: "ground",
  },
  attacks: {
    main: {
      type: "projectile",
      anim: "attack-B",
      power: 1,
      damage: 1,
      antiAir: true,
      projectile: {
        texture: "vfx-rainbowball",
        anim: "vfx-rainbowball",
        speed: 260,
        offsetX: 70,
        offsetY: 28,
        lifetime: 1200,
      },
      fireFrame: 8,
      cooldown: 800,
    },
    skill1: {
      type: "projectile",
      anim: "attack-C",
      power: 1,
      damage: 1,
      punish: true,
      desperation: true,
      hitStop: 110,
      impactVFX: "impact-hit",
      projectile: {
        texture: "vfx-rainbowball",
        anim: "vfx-rainbowball",
        speed: 260,
        offsetX: 33,
        offsetY: 50,
        lifetime: 1200,
      },
      fireFrame: 5,
      cooldown: 800,
    },
  },
  evolution: {
    prev: null,
    next: "patamon",
  },
};
