export const patamon = {
  body: {
    width: 15,
    height: 14,
    offsetX: 0,
    offsetY: 0,
    gravityY: 900,
  },
  movement: {
    mode: "multi-domain",
    domains: ["ground", "air"],
    default: "ground",
  },
  attacks: {
    main: {
      type: "projectile",
      anim: "attack-B",
      power: 0.5,
      damage: 1,
      hitStop: 50,
      impactVFX: "vfx-explosion",
      projectile: {
        texture: "vfx-windball",
        anim: "vfx-windball",
        scale: 0.3,
        speed: 260,
        offsetX: 33,
        offsetY: 1,
        lifetime: 1200,
        hitReaction: "flinch",
      },
      fireFrame: 6,
      cooldown: 800,
    },
    skill1: {
      type: "projectile",
      anim: "attack-C",
      power: 0.8,
      damage: 1,
      hitStop: 50,
      impactVFX: "vfx-explosion",
      projectile: {
        texture: "vfx-windball",
        anim: "vfx-windball",
        scale: 0.3,
        speed: 260,
        offsetX: 25,
        offsetY: 20,
        lifetime: 1200,
      },
      fireFrame: 4,
      cooldown: 800,
    },
  },
  evolution: {
    prev: null,
    next: "greymon",
  },
};
